# Generated by Django 2.2.12 on 2021-01-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('question_video', models.FileField(upload_to='media')),
                ('question_text', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=100)),
                ('user_answer', models.CharField(blank=True, max_length=100)),
                ('percentage', models.IntegerField(blank=True)),
            ],
        ),
    ]
